// <auto-generated />
namespace DL.Migrations.Shop
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class poprawka_oceny_float : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poprawka_oceny_float));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041428304_poprawka_oceny_float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
